apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sameep-code
  namespace: gp-engine-malof
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sameep-results
  namespace: gp-engine-malof
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
