apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sameep-code-new
  namespace: gp-engine-malof
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-cephfs-central
