apiVersion: batch/v1
kind: Job
metadata:
  name: sameep-job1
  namespace: gp-engine-malof
spec:
  template:
    spec:
      containers:
        - name: dev
          image: docker.io/saadlahrichi/fire:v6
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "🔍 Checking GPU Memory..."
              MEM=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -n 1)
              echo "🧠 GPU Memory Detected: $MEM MiB"
              if [ "$MEM" -lt 22000 ]; then
                echo "❌ GPU too small (<22GB). Exiting."
                exit 1
              elif [ "$MEM" -gt 33000 ]; then
                echo "⚠️ GPU too large (>32GB). Skipping to avoid waste. Exiting."
                exit 1
              else
                echo "✅ Suitable GPU ($MEM MiB). Starting training..."
              fi
              sleep infinity
          resources:
            limits:
              cpu: "20"
              memory: 200Gi
              nvidia.com/gpu: 1
            requests:
              cpu: "20"
              memory: 200Gi
              nvidia.com/gpu: 1
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
          volumeMounts:
            - name: code-volume
              mountPath: /develop/code
            - name: results-volume
              mountPath: /develop/results
            - name: fire-data
              mountPath: /develop/data
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: code-volume
          persistentVolumeClaim:
            claimName: sameep-code-new
        - name: results-volume
          persistentVolumeClaim:
            claimName: sameep-results-new
        - name: fire-data
          persistentVolumeClaim:
            claimName: fire-data
        - name: dshm
          emptyDir:
            medium: Memory
      restartPolicy: Never
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/gp-engine-malof"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "nautilus.io/issue"
          operator: "Exists"
          effect: "NoSchedule"
  backoffLimit: 0
