apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sameep-workspace
  namespace: gp-engine-malof
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: rook-cephfs-central
